export const devices = [
  {
    index: 1,
    name: 'Pet Cleaner C1',
    id: 'JR-84VIETNAM',
    status: 'Connected',
    version: '1.8.7',
    info: 'good',
    manufacturer: 'PetCare',
    policy: 'Use data only to build better services',
  },
  // {
  //   index: 2,
  //   name: 'Pet Feeder M1',
  //   id: 'SM-F57NA45/M1',
  //   status: 'Connected',
  //   version: '1.1.1',
  //   info: 'good',
  //   manufacturer: 'PetCare',
  //   policy: 'Use data only to build better services',
  // },
  // {
  //   index: 3,
  //   name: 'Dispenser F2',
  //   id: 'TM-12GERMANY',
  //   status: 'Connected',
  //   version: '2.6.3',
  //   info: 'good',
  //   manufacturer: 'PetCare',
  //   policy: 'Use data only to build better services',
  // },
];
